"use client";

import React, { useEffect, useRef } from "react";
import { Link, Element } from "react-scroll";
import {
  Grid2 as Grid,
  Typography,
  Link as MuiLink,
  Box,
  alpha,
  darken,
  List,
  ListItem,
  BoxProps,
  Divider,
} from "@mui/material";
import { StaticImport } from "next/dist/shared/lib/get-img-props";
import Image from "next/image";
import uploadButton from "/public/upload-button.png";
import uploadVariantsButton from "/public/upload-variants-button.png";
import variantDropdown from "/public/variant-dropdown.png";
import miamiDynamic from "/public/miami-dynamic-y.png";
import miamiOverflow1 from "/public/miami-overflow-1.png";
import miamiOverflow2 from "/public/miami-overflow-2.png";
import qqPlot from "/public/qq-plot.png";
import regionAnnotation from "/public/region-plot-annotation.png";
import plinkPlot from "/public/plink-plot.png";

const Page: React.FC = () => {
  const tocRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const shiftSticky = () => {
      if (tocRef.current) {
        const scrollTop = window.scrollY;
        if (scrollTop > 50) {
          tocRef.current.style.top = "20px";
        } else {
          tocRef.current.style.top = "auto";
        }
      }
    };

    window.addEventListener("scroll", shiftSticky);
    return () => {
      window.removeEventListener("scroll", shiftSticky);
    };
  }, []);

  return (
    <Grid container direction="row" spacing={4} justifyContent="center">
      <Grid container justifyContent="center" direction="row" size={{ xs: 12 }}>
        <Grid>
          <Typography textAlign="center" variant="h2">
            User Guide
          </Typography>
        </Grid>
      </Grid>
      <Grid
        container
        direction="row"
        size={{ xs: 2.5 }}
        sx={(theme) => ({
          [theme.breakpoints.down("md")]: { display: "none" },
        })}
        justifyContent="flex-start"
      >
        <Box position="relative">
          <Box position="fixed" ref={tocRef}>
            <List
              sx={(theme) => ({
                "a.active-link": {
                  color: theme.palette.primary.light,
                },
              })}
            >
              <TocItem target="uploading-data">Uploading Data</TocItem>
              <TocItem target="miami-plot">The Miami Plot</TocItem>
              <TocItem target="qq-plot">The QQ Plot</TocItem>
              <TocItem target="region-plot">The Region Plot</TocItem>
              <TocItem target="performance">Performance</TocItem>
            </List>
          </Box>
        </Box>
      </Grid>
      <Grid
        container
        maxWidth="1200px"
        direction="column"
        spacing={3}
        size={{ xs: 12, md: 9.5 }}
      >
        <Grid
          component={Element}
          name="uploading-data"
          container
          direction="column"
          spacing={1}
        >
          <Grid>
            <Typography variant="h4">1. Uploading Data</Typography>
          </Grid>
          <Grid container direction="column">
            <Grid>
              <Typography variant="h6">Data requirements</Typography>
            </Grid>
            <Grid>
              <Typography>
                The dashboard is designed to render results generated by{" "}
                <MuiLink
                  target="_blank"
                  href="https://github.com/brossardMyriam/RegionScan"
                >
                  RegionScan: A comprehensive R package for region-level
                  genome-wide association testing with integration and
                  visualization of multiple-variant and single-variant
                  hypothesis testing
                </MuiLink>
                . The dashboard can use both region-level results and the
                corresponding variant-level results for the same regions. All
                analyses and field names and value ranges are expected to match
                those of RegionScan outputs. Suumary output files may be in .csv
                or .tsv format. The current list of supported column names for
                region-level output files is{" "}
              </Typography>
            </Grid>
            <Grid container justifyContent="center">
              <FieldNameGrid
                names={[
                  "region",
                  "chr",
                  "start.bp",
                  "end.bp",
                  "nSNPs",
                  "nSNPs.kept",
                  "maxVIF",
                  "Wald",
                  "Wald.df",
                  "Wald.p",
                  "PC80",
                  "PC80.df",
                  "PC80.p",
                  "MLCB",
                  "MLCB.df",
                  "MLCB.p",
                  "LCB",
                  "LCB.df",
                  "LCB.p",
                  "MLCZ",
                  "MLCZ.df",
                  "MLCZ.p",
                  "LCZ",
                  "LCZ.df",
                  "LCZ.p",
                  "SKAT",
                  "SKAT.p",
                  "SKATO.p",
                  "simes.p",
                  "simpleM.df",
                  "simpleM.p",
                  "SKAT.pLiu",
                  "SKATO.pOptadj",
                  "GATES.p",
                  "single_Walkd.p",
                  "gene",
                ]}
              />
            </Grid>
            <Grid>
              <Typography>
                The current list of supported column names for RegionScan
                variant-level output files is:{" "}
              </Typography>
              <Grid container justifyContent="center">
                <FieldNameGrid
                  names={[
                    "chr",
                    "region",
                    "start.bp",
                    "end.bp",
                    "bin",
                    "bp",
                    "pos",
                    "multiallelic",
                    "ref",
                    "alt",
                    "maf",
                    "MLC.codechange",
                    "LC.codechange",
                    "variant",
                    "sglm.beta",
                    "sglm.se",
                    "sglm.pvalue",
                    "mglm.vif",
                    "mglm.beta",
                    "mglm.se",
                    "mglm.pvalue",
                    "gene",
                  ]}
                />
              </Grid>
            </Grid>
            <Grid>
              <Typography>
                <Strong>Notes</Strong>: The dashboard is flexible and can also
                handle:
              </Typography>
              <List>
                <ListItem>
                  <Typography>
                    • Additional p-values for both region-level and
                    variant-level files obtained using other tests (e.g. from
                    additional tools or packages, such as{" "}
                    <MuiLink
                      href="https://github.com/yaowuliu/ACAT"
                      target="_blank"
                    >
                      ACAT
                    </MuiLink>{" "}
                    or{" "}
                    <MuiLink
                      href="https://rgcgithub.github.io/regenie/"
                      target="_blank"
                    >
                      REGENIE
                    </MuiLink>
                    ) provided that the p-value column names end with “.p” (e.g.
                    ACAT.p).{" "}
                  </Typography>
                </ListItem>
                <ListItem>
                  <Typography>
                    • Results based on gene-level analyses instead of
                    non-overlapping LD block regions.
                  </Typography>
                </ListItem>
              </List>
            </Grid>
          </Grid>
          <Grid container spacing={1} direction="column">
            <Grid>
              <Typography variant="h6">Uploading data</Typography>
            </Grid>
            <Grid>
              <Typography>
                Use the UPLOAD DATA button at the top of the screen to load your
                files. Note that you may select more than one file (For example,
                for multiple chromosomes), but subsequent uploads will overwrite
                all data currently loaded into the dashboard.
              </Typography>
            </Grid>
            <GridImage
              alt={"upload button"}
              height={174}
              src={uploadButton}
              width={1179}
              widthPct="75%"
            />
            <Grid>
              <Typography>
                Once the region-level files are uploaded, you may upload
                variant-level files using the same interface.
              </Typography>
            </Grid>
            <GridImage
              alt={"upload variant button"}
              height={263}
              src={uploadVariantsButton}
              width={1186}
              widthPct="75%"
            />
            <Grid>
              <Typography>
                If your variant file contains data for the range covered by the
                region file(s) you have uploaded, you will be able to add{" "}
                "sglm_pvalue" to the plot
              </Typography>
            </Grid>
            <GridImage
              widthPct="25%"
              height={463}
              width={504}
              alt="variant dropdown"
              src={variantDropdown}
            />
          </Grid>
          <SectionDivider />
        </Grid>
        <Grid
          container
          component={Element}
          name="miami-plot"
          direction="column"
        >
          <Grid>
            <Typography variant="h4">2. The Miami Plot</Typography>
          </Grid>
          <Grid>
            <Typography>
              The dropdown controls can be used to select two region-level tests
              to compare p-values in the <Strong>Miami plot</Strong>. By
              default, the domains of the y-axes are dynamically calculated for
              both plots. To use the same y-axis domain for both plots, use the
              toggle <Italic>static</Italic> in the settings dropdown.
            </Typography>
          </Grid>
          <GridImage
            width={1128}
            height={513}
            widthPct="50%"
            alt="Miami Y toggle"
            src={miamiDynamic}
          />
          <Grid>
            <Typography>
              In case of outliers, a separate y-axis can be rendered after a
              certain threshold. Use the controls in the settings dropdown to
              set the threshold of the p-value as well as the number of pixels
              to give to the second, "overflow" axis.
            </Typography>
          </Grid>
          <GridImage
            src={miamiOverflow1}
            width={1123}
            height={662}
            alt="Miami plot y overflow 1"
            widthPct="50%"
          />
          <GridImage
            src={miamiOverflow2}
            width={956}
            height={499}
            alt="Miami plot y overflow 2"
            widthPct="50%"
          />
          <SectionDivider />
        </Grid>
        <Grid container direction="column" component={Element} name="qq-plot">
          <Grid>
            <Typography variant="h4">3. The QQ Plot</Typography>
          </Grid>
          <Grid>
            <Typography>
              <Strong>The QQ Plot</Strong> renders observed p-values against
              expected p-values taken from the uniform distribution of random
              variables over the same range for each test. Region-level tests
              can be added or removed from the plot using the checkboxes.
            </Typography>
          </Grid>
          <GridImage
            height={476}
            width={488}
            widthPct="40%"
            src={qqPlot}
            alt="qq-plot"
          />
          <SectionDivider />
        </Grid>
        <Grid
          container
          direction="column"
          component={Element}
          name="region-plot"
        >
          <Grid>
            <Typography variant="h4">4. The Region Plot</Typography>
          </Grid>
          <Grid>
            <Typography>
              Click on any region in the Miami plot to show the{" "}
              <Strong>Region Plot</Strong>, a detailed rendering of a particular
              region.
            </Typography>
          </Grid>
          <Grid>
            <Typography>
              By default, the region plot shows a 40-region range. Zoom in or
              out by scrolling the mouse wheel or entering the new range in the
              input boxes. The plot can also be dragged left or right.
            </Typography>
          </Grid>
          <Grid>
            <Typography>
              Use the ANNOTATION CONTROLS button to change the appearance of the
              plot. If variants are loaded for the region, their visibility can
              be toggled here. Region labels can also be toggled, along with the
              recombination rate plot line.
            </Typography>
          </Grid>
          <Grid>
            <Typography>
              Click the FETCH GENES button to fetch genes for the region from
              the{" "}
              <MuiLink href="https://rest.ensembl.org/documentation/info/overlap_region">
                Ensembl REST API
              </MuiLink>
              . By default, only protein-coding genes are shown. To show
              non-protein-coding genes and to toggle gene name visibility, use
              the annotation controls.
            </Typography>
          </Grid>
          <GridImage
            src={regionAnnotation}
            height={622}
            width={2025}
            widthPct="75%"
            alt="region-annotations"
          />
          <Grid container>
            <Typography>
              Variants from a PLINK analysis can be uploaded via the UPLOAD
              PLINK VARIANT FILE button. Currently PLINK files require the
              following fields:
            </Typography>
          </Grid>
          <Grid container justifyContent="center">
            <FieldNameGrid names={["chrom", "pos", "ref", "alt", "test"]} />
          </Grid>
          <Grid>
            <Typography>
              Currently, only variants with test type <Code>ADD</Code> will be
              rendered.
            </Typography>
          </Grid>
          <GridImage
            width={2074}
            height={598}
            widthPct="75%"
            alt="Region plink plot"
            src={plinkPlot}
          />
          <SectionDivider />
        </Grid>
        <Grid
          container
          direction="column"
          component={Element}
          name="performance"
        >
          <Grid>
            <Typography variant="h4">5. Performance</Typography>
          </Grid>
          <Grid>
            <Typography>
              The application will become slower and the visualizations less
              responsive as more data are rendered in the browser. For instance,
              viewing the entire genome in the Miami plot will be slower than
              viewing a small range in a single chromosome.
            </Typography>
            <Typography>
              There are a few ways to improve performance:{" "}
            </Typography>
            <List>
              <ListItemBlock>
                <Typography>
                  <Strong>Load only the data you need</Strong>
                </Typography>
                <Typography>
                  If you have identified a region of interest, upload only the
                  files associated with that region.
                </Typography>
              </ListItemBlock>
              <ListItemBlock>
                <Typography>
                  <Strong>Zoom in on the Miami plot</Strong>
                </Typography>
                <Typography>
                  Drag the mouse to select the area of the Miami plot you are
                  interested in. This will reduce the number of data points
                  rendered.
                </Typography>
              </ListItemBlock>
              <ListItemBlock>
                <Typography>
                  <Strong>Hide the QQ Plot</Strong>
                </Typography>
                <Typography>
                  The QQ Plot can grow to a large size with a large dataset. Try
                  hiding unneeded variables or hiding the plot completely by
                  clicking the gear icon and toggling the "Show QQ Plot" option.
                </Typography>
              </ListItemBlock>
              <ListItemBlock>
                <Typography>
                  <Strong>View the Miami Plot as an area plot</Strong>
                </Typography>
                <Typography>
                  When looking at large amount of data, consider viewing the
                  Miami plot as an area plot. This will reduce the amount of
                  data in the image at the expense of detail. It may be most
                  useful when viewing a large range, as peaks will still be
                  visible. You can do this by clicking the gear icon and
                  selecting the "Area" option under "Miami Plot Type." Zooming
                  is much faster with the area plot. After identifying an area
                  of interest, you can toggle the Miami Plot back to "Scatter"
                  and select a region to view in the region plot.
                </Typography>
              </ListItemBlock>
            </List>
          </Grid>
        </Grid>

        {/*<Grid>
          <Typography variant="h5">Exporting</Typography>
        </Grid>
        <Grid>
          <Typography variant="h4">Tips and tricks</Typography>
        </Grid> */}
      </Grid>
    </Grid>
  );
};

const ListItemBlock = ({ children, ...props }: BoxProps) => (
  <Box component={ListItem} {...props} display="block">
    {children}
  </Box>
);

interface FieldNameGridProps {
  names: string[];
  sort?: boolean;
}

const FieldNameGrid: React.FC<FieldNameGridProps> = ({ names, sort }) => (
  <Grid
    container
    direction="row"
    justifyContent="center"
    spacing={1}
    sx={(theme) => ({
      backgroundColor: alpha(theme.palette.info.light, 0.3),
      padding: 2,
      borderRadius: 2,
      margin: 3,
      width: "75%",
      maxWidth: "800px",
    })}
  >
    {names
      .sort((a, b) =>
        !!sort ? (a.toLowerCase() < b.toLowerCase() ? -1 : 1) : 0,
      )
      .map((d) => (
        <Grid key={d}>
          <Box component="pre" margin={0.5}>
            {d}
          </Box>
        </Grid>
      ))}
  </Grid>
);

const Strong: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Box component="span" fontWeight="bold">
    {children}
  </Box>
);

const Italic: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Box component="span" fontStyle="italic">
    {children}
  </Box>
);

const Code: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <Box
    component="span"
    color={(theme) => darken(theme.palette.secondary.dark, 0.2)}
    margin="inherit"
    display="inline"
    fontFamily="monospace"
  >
    {children}
  </Box>
);

interface GridImageProps {
  alt: string;
  height: number;
  src: StaticImport;
  width: number;
  widthPct: string;
}

const GridImage: React.FC<GridImageProps> = ({
  alt,
  height,
  src,
  width,
  widthPct,
}) => (
  <Grid
    size={{ xs: 12 }}
    direction="row"
    flexGrow={1}
    margin={2}
    container
    justifyContent="center"
    sx={{
      img: {
        minWidth: "300px",
        width: widthPct,
        height: "auto",
      },
    }}
  >
    <Grid textAlign="center">
      <Image
        alt={alt}
        height={height}
        priority={false}
        src={src}
        width={width}
      />
    </Grid>
  </Grid>
);

const SectionDivider: React.FC = () => (
  <Grid padding={3}>
    <Divider />
  </Grid>
);

const TocItem: React.FC<{ children: React.ReactNode; target: string }> = ({
  children,
  target,
}) => (
  <ListItem>
    <Link spy activeClass="active-link" to={target}>
      <Typography sx={{ cursor: "pointer" }} variant="h6">
        {children}
      </Typography>
    </Link>
  </ListItem>
);

export default Page;
