name: Check NextJS
on:
  pull_request:
    branches:
      - master

jobs:
  check-next:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: next
      -
        name: Install packages
        working-directory: next/region-scan-dashboard
        run: |
          npm ci
      -
        name: Check React formatting
        working-directory: next/region-scan-dashboard
        run: |
          npm run format-check
      -
        name: Lint React code
        working-directory: next/region-scan-dashboard
        run: |
          npm run lint-check
      -
        name: Check typescript
        working-directory: next/region-scan-dashboard
        run: |
          npm run type-check

